name: mimir
version: 1.0.0

description: 'Mímir.'

homepage: https://github.com/liplum/mimir
repository: https://github.com/liplum/mimir
issue_tracker: https://github.com/liplum/mimir/issues
documentation: https://github.com/liplum/mimir#readme

publish_to: none
environment: { sdk: '>=2.18.1 <3.0.0', flutter: ^3.0.0 }

dependencies:

  flutter: { sdk: flutter }

  device_info_plus_platform_interface: ^7.0.0
  # I18n
  intl: ^0.17.0
  easy_localization: ^3.0.2

  # Basic
  logger: ^1.1.0              # logger
  path_provider: ^2.0.8       # Path

  # String and charset
  format: ^1.1.1              # String formatting

  # Cryptography
  encrypt: ^5.0.1             # Encryption (AES)
  crypto: ^3.0.1              # Hash (MD5)
  uuid: ^3.0.5                # UUID generator

  # File format
  ical: ^0.2.2                # iCalendar file generator
  json_serializable: ^6.3.1   # JSON
  json_annotation: ^4.6.0     # JSON code generation
  beautiful_soup_dart: ^0.3.0 # HTML parser

  # hive (key-value database)
  hive: ^2.0.5
  hive_flutter: ^1.1.0

  # Dio (http client)
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0

  # WebView and browser related
  webview_flutter: ^4.2.1
  fk_user_agent: ^2.1.0
  flutter_widget_from_html: ^0.10.1

  # Email
  enough_mail: ^2.1.0
  enough_mail_html: ^2.0.0

  # Settings
  app_settings: ^4.1.1
  flutter_settings_screens: ^0.3.3-null-safety+2

  # Platform
  permission_handler: ^10.2.0        # Android / iOS / Windows Permission
  quick_actions: ^1.0.1           # Android / iOS Home screen quick actions

  # Open with other APP/programs
  open_file: ^3.2.1                 # Open files
  url_launcher: ^6.0.17             # Open URLs
  image_picker: ^0.8.4+7            # Open Android / iOS system image picker
  file_picker: 5.0.0

  # UI
  fl_chart: ^0.55.0
  grouped_list: ^5.1.1
  pull_to_refresh: ^2.0.0
  dynamic_color_theme: ^2.0.0
  geopattern_flutter: { git: { url: https://github.com/paolovalerdi/geopattern } }
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.5.2              # Screen adaptation
  qr_flutter: ^4.0.0                      # Qr code generate
  mobile_scanner: ^2.1.0                  # qrcode scanner
  audioplayers: ^3.0.1                   # audio player
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.1
  flutter_easyloading: ^3.0.5
  animated_button_bar: ^0.0.2

  # Utils
  version: ^3.0.2               # Version comparison
  flutter_phoenix: ^1.1.0       # Soft-restart app
  package_info_plus: ^3.0.0     # Get package info (version)
  universal_platform: ^1.0.0+1  # dart.io.Platform API for Web
  check_vpn_connection: ^0.0.2  # Check VPN connection status
  synchronized: ^3.0.0+2        # lock
  stack_trace: ^1.10.0          # parse stacktrace

  # Desktop support
  window_manager: ^0.2.0

  flutter_html: ^3.0.0-alpha.6
  vibration: ^1.7.6
  animations: ^2.0.7
  rettulf: ^0.0.13
  auto_animated: ^3.1.0
  markdown: ^6.0.1
  event_bus: ^2.0.0
  collection: ^1.16.0
  rnd: ^0.2.0
  animated_size_and_fade: ^3.0.0
  unicons: ^2.1.0
  loading_animation_widget: ^1.2.0+3
  connectivity_plus: ^3.0.3
  modal_bottom_sheet: ^3.0.0-pre
  msh_checkbox: ^1.2.1
  animated_toggle_switch: ^0.5.2
  quiver: ^3.1.0
  auto_size_text: ^3.0.0
  cookie_jar: ^3.0.1
  flutter_widget_from_html_core: ^0.10.1
  yaml: ^3.1.1
  path: ^1.8.2

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  hive_generator: ^2.0.0

# ------------------------------------------------------------------------------

flutter:

  uses-material-design: true
  fonts:
    # Iconfont for ywb.sit.edu.cn
    # For office module. So I named it office_iconfont.
    - family: office_iconfont
      fonts: [ { asset: assets/fonts/office_iconfont.ttf } ]

  assets:
    - assets/
    - assets/common/
    - assets/home/
    - assets/connectivity/
    - assets/report_temp/
    - assets/fonts/
    - assets/library/
    - assets/timetable/
    - assets/course/
    - assets/edu_email/
    - assets/scanner/
    - assets/scanner/beep.mp3
    - assets/yellow_pages.json
    - assets/room_list.json
    - assets/webview/
    - assets/l10n/

flutter_intl:
  enabled: true
