name: mimir
version: 1.0.0

description: 'Mímir.'

homepage: https://github.com/liplum/mimir
repository: https://github.com/liplum/mimir
issue_tracker: https://github.com/liplum/mimir/issues
documentation: https://github.com/liplum/mimir#readme

publish_to: none
environment: { sdk: '>=3.0.0 <4.0.0', flutter: ^3.0.0 }

dependencies:

  flutter: { sdk: flutter }

  device_info_plus: ^9.0.3
  audio_session: ^0.1.16

  # I18n
  intl: ^0.17.0
  easy_localization: ^3.0.3

  # Basic
  logger: ^1.1.0              # logger
  path_provider: ^2.0.15       # Path
  version: ^3.0.2               # Version comparison
  yaml: ^3.1.2
  path: ^1.8.2
  quiver: ^3.1.0
  collection: ^1.17.2
  format: ^1.3.0              # String formatting
  go_router: ^10.1.2
  rettulf: ^1.0.1
  event_bus: ^2.0.0

  # Cryptography
  encrypt: ^5.0.1             # Encryption (AES)
  crypto: ^3.0.3              # Hash (MD5)
  uuid: ^3.0.7                # UUID generator

  # File format
  ical: ^0.2.2                # iCalendar file generator
  json_serializable: ^6.7.1   # JSON
  json_annotation: ^4.8.1     # JSON code generation
  beautiful_soup_dart: ^0.3.0 # HTML parser

  # hive (key-value database)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Dio (http client)
  dio: ^5.3.2
  dio_cookie_manager: ^3.1.0+1

  # WebView and browser related
  webview_flutter: ^4.2.4
  fk_user_agent: ^2.1.0
  flutter_widget_from_html: ^0.10.4
  chewie: ^1.7.0
  cookie_jar: ^4.0.8
  flutter_widget_from_html_core: ^0.10.4
  flutter_html: ^3.0.0-beta.2

  # Email
  enough_mail: ^2.1.1
  enough_mail_html: ^2.0.0

  # Settings
  app_settings: ^5.0.0

  # Platform
  permission_handler: ^10.4.3        # Android / iOS / Windows Permission
  quick_actions: ^1.0.6           # Android / iOS Home screen quick actions

  # Open with other APP/programs
  open_file: ^3.3.2                 # Open files
  url_launcher: ^6.1.14             # Open URLs
  image_picker: ^1.0.4            # Open Android / iOS system image picker
  file_picker: ^5.5.0
  share_plus: ^7.1.0

  # UI
  fl_chart: ^0.63.0
  grouped_list: ^5.1.2
  pull_to_refresh: ^2.0.0
  geopattern_flutter: { git: { url: https://github.com/paolovalerdi/geopattern } }
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.9.0              # Screen adaptation
  qr_flutter: ^4.1.0                      # Qr code generate
  mobile_scanner: ^3.4.1                  # qrcode scanner
  cached_network_image: ^3.2.3
  flutter_easyloading: ^3.0.5
  modal_bottom_sheet: ^3.0.0-pre
  auto_size_text: ^3.0.0
  markdown: ^7.1.0
  auto_animated: ^3.1.0
  animations: ^2.0.7
  dynamic_color: ^1.6.6
  unicons: ^2.1.1

  # Utils
  package_info_plus: ^4.1.0     # Get package info (version)
  universal_platform: ^1.0.0+1  # dart.io.Platform API for Web
  check_vpn_connection: ^0.0.2  # Check VPN connection status
  connectivity_plus: ^3.0.3
  synchronized: ^3.1.0        # lock
  stack_trace: ^1.11.0          # parse stacktrace
  email_validator: ^2.1.17
  vibration: ^1.8.1

  # Desktop support
  window_manager: ^0.3.6


dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  hive_generator: ^2.0.0

# ------------------------------------------------------------------------------

flutter:

  uses-material-design: true
  fonts:
    # Iconfont for ywb.sit.edu.cn
    - family: ywb_iconfont
      fonts: [ { asset: assets/fonts/ywb_iconfont.ttf } ]

  assets:
    - assets/
    - assets/home/
    - assets/fonts/
    - assets/library/
    - assets/timetable/
    - assets/course/
    - assets/yellow_pages.json
    - assets/room_list.json
    - assets/webview/
    - assets/l10n/

flutter_intl:
  enabled: true
