name: push release

on: push

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore cache builds(apk)
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/builds/
          key: build-apk-
      
      - name: Restore cache builds(ipa)
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/builds/
          key: build-ipa-

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ~/builds/*.apk
            ~/builds/*.ipa
          tag_name: ${{ github.ref }}
          body: '这里是body'
          draft: true
          prerelease: false
    
      - name: Delete cache builds
        run:
            gh cache delete build-apk-*
            gh cache delete build-ipa-*
