name: Release new version

on:
  release:
    types: [released]

permissions: 
    contents: read
    packages: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Install deploy key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DOCS_SSH_KEY }}
          known_hosts: ${{ secrets.DOCS_KNOWN_HOST }}

      - name: Deploy
        # if: github.repository == 'liplum-dev/mimir'
        shell: bash
        run: |
          git clone --single-branch --branch main "https://github.com/Amazefcc233/mimir-docs" ~/deploy
          cd ~/deploy

          version=$(echo "${{ github.event.release.tag_name }}" | sed 's/v//g')
          release_time=$(echo "${{ github.event.release.published_at }}" | sed 's/T/ /g' | sed 's/Z//g')
          release_time=$(date -d "$release_time 8 hours" "+%Y-%m-%d %H:%M:%S")
          apk_name=$(echo "${{ github.event.release.assets[0].name }}")
          apk_url=$(echo "${{ github.event.release.assets[0].browser_download_url }}")
          ipa_name=$(echo "${{ github.event.release.assets[1].name }}")
          ipa_url=$(echo "${{ github.event.release.assets[1].browser_download_url }}")
          release_note=$(echo "${{ github.event.release.body }}" | sed -n '/## 更改/,/## How to download/p' | sed '1d;$d')
          echo "$release_note"
  