name: 3.Release New Version

on:
  release:
    types: [ released ]

permissions:
  contents: read
  packages: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Install deploy key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DOCS_SSH_KEY }}
          known_hosts: ${{ secrets.DOCS_KNOWN_HOST }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: tools/package-lock.json

      - name: Setup git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy
        if: github.repository == 'liplum-dev/mimir'
        shell: bash
        run: |
          node tools/publish-release.mjs
